#!/usr/bin/env bash

_genrandom(){
   echo -n $(openssl rand -base64 10 | tr -d "=+/" | cut -c -5)
}

for i in {1..3}; do
   _genrandom
   
   if [ $i -eq 3 ]; then
      echo ""
      break
   fi
   
   echo -n "-"
done

